### ISSUE TITLE
build fails due to no strict mode

### ISSUE THREAD

**Issue by acthp** [alexhisen/mobx-forms-demo#1]
npm install
npm start
let moduleValuesPlugin = require('postcss-modules-values-replace');
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by alexhisen** [comment]
Hmm. I just tested it with fresh npm_modules and can't seem to replicate this issue. Most likely your node version is too old and doesn't support ES6.
